// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KER9GhTbMoN8XHXVIiErKhkaXct9nbw',
    authDomain: 'patente-b-2025.firebaseapp.com',
    projectId: 'patente-b-2025',
    storageBucket: 'patente-b-2025.firebasestorage.app',
    messagingSenderId: '816270740093',
    appId: '1:816270740093:web:90a21eb0c7054e0824ff14',
    measurementId: 'G-WXD3BJEJ6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2KER9GhTbMoN8XHXVIiErKhkaXct9nbw',
    authDomain: 'patente-b-2025.firebaseapp.com',
    projectId: 'patente-b-2025',
    storageBucket: 'patente-b-2025.firebasestorage.app',
    messagingSenderId: '816270740093',
    appId:
        '1:816270740093:android:90a21eb0c7054e0824ff14', // Note: Android appId may differ
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2KER9GhTbMoN8XHXVIiErKhkaXct9nbw',
    authDomain: 'patente-b-2025.firebaseapp.com',
    projectId: 'patente-b-2025',
    storageBucket: 'patente-b-2025.firebasestorage.app',
    messagingSenderId: '816270740093',
    appId:
        '1:816270740093:ios:90a21eb0c7054e0824ff14', // Note: iOS appId may differ
    iosBundleId: 'com.kmrnnwr.patenteB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2KER9GhTbMoN8XHXVIiErKhkaXct9nbw',
    authDomain: 'patente-b-2025.firebaseapp.com',
    projectId: 'patente-b-2025',
    storageBucket: 'patente-b-2025.firebasestorage.app',
    messagingSenderId: '816270740093',
    appId: '1:816270740093:ios:90a21eb0c7054e0824ff14',
    iosBundleId: 'com.kmrnnwr.patenteB',
  );
}
